[phases.setup]
nixPkgs = ["nodejs_20", "npm-9_x"]

[phases.install]
cmds = ["npm ci --production=false"]

[phases.build]
cmds = ["npx tsc", "cd ui && npm ci --production=false && npx vite build --emptyOutDir"]

[start]
cmd = "node dist/server.js"
