import { GenomicAnalyzer } from '../../src/genomics/analyzer.js';
import type { GenomicProfile } from '../../src/genomics/analyzer.js';

// ── Mock 23andMe data helper ─────────────────────────────────────

/**
 * Generate a valid 23andMe v5 raw-data string with known genotypes.
 *
 * Includes:
 *  - rs429358 CT + rs7412 CC  => APOE e3/e4
 *  - CYP2D6 star-allele SNPs for Poor Metaboliser
 *  - CYP2C19 star-allele SNPs for Normal Metaboliser
 *  - Additional risk SNPs
 */
function make23andMeFile(): string {
  const header = [
    '# This data file generated by 23andMe at: Mon Jan 01 00:00:00 2024',
    '#',
    '# Below is a text version of your data.',
    '# Fields are TAB-separated',
    '# rsid\tchromosome\tposition\tgenotype',
  ].join('\n');

  // Key pharmacogenomic SNPs
  const snps: Array<[string, string, number, string]> = [
    // APOE: rs429358=CT, rs7412=CC => e3/e4
    ['rs429358', '19', 45411941, 'CT'],
    ['rs7412', '19', 45412079, 'CC'],

    // CYP2D6 SNPs — *4/*4 poor metaboliser pattern
    ['rs3892097', '22', 42524947, 'AA'], // *4 homozygous splice defect
    ['rs1065852', '22', 42522613, 'AA'], // *10 homozygous
    ['rs16947', '22', 42523943, 'CC'],   // wild-type for *2
    ['rs1135840', '22', 42523805, 'GG'], // *1 reference

    // CYP2C19 SNPs — *1/*1 normal metaboliser
    ['rs4244285', '10', 96541616, 'GG'], // *1/*1 (no *2)
    ['rs4986893', '10', 96540410, 'GG'], // no *3
    ['rs12248560', '10', 96521657, 'CC'], // no *17

    // COMT
    ['rs4680', '22', 19951271, 'AG'],

    // MTHFR
    ['rs1801133', '1', 11856378, 'AG'],

    // Extra risk SNPs for biomarker scoring
    ['rs1229984', '4', 100239319, 'CT'],
    ['rs671', '12', 112241766, 'GG'],
    ['rs1800497', '11', 113283459, 'AG'],
    ['rs4420638', '19', 45422946, 'AG'],
    ['rs6983267', '8', 128413305, 'GT'],
    ['rs10757278', '9', 22125503, 'AG'],
    ['rs1333049', '9', 22125004, 'CG'],
    ['rs2187668', '6', 32713862, 'CT'],
    ['rs9272219', '6', 32714032, 'AG'],
    ['rs1801282', '3', 12393125, 'CG'],
  ];

  const lines = snps.map(([rsid, chr, pos, gt]) => `${rsid}\t${chr}\t${pos}\t${gt}`);
  return header + '\n' + lines.join('\n') + '\n';
}

// ── Tests ────────────────────────────────────────────────────────

describe('GenomicAnalyzer', () => {
  let analyzer: GenomicAnalyzer;
  let profile: GenomicProfile;

  beforeAll(() => {
    analyzer = new GenomicAnalyzer();
    profile = analyzer.analyze(make23andMeFile(), 'subject-001');
  });

  it('should parse all markers from the mock file', () => {
    expect(profile.totalMarkers).toBeGreaterThanOrEqual(20);
    expect(profile.subjectId).toBe('subject-001');
    expect(profile.build).toBeDefined();
  });

  describe('CYP2D6 pharmacogenomics', () => {
    it('should detect a non-Normal CYP2D6 phenotype from *4-like SNPs', () => {
      expect(profile.cyp2d6.phenotype).toBeDefined();
      expect(typeof profile.cyp2d6.activity).toBe('number');
      expect(profile.cyp2d6.allele1).toBeDefined();
      expect(profile.cyp2d6.allele2).toBeDefined();
    });
  });

  describe('CYP2C19 pharmacogenomics', () => {
    it('should detect Normal CYP2C19 metaboliser from *1/*1 SNPs', () => {
      // With GG at rs4244285 and GG at rs4986893, expect Normal
      expect(profile.cyp2c19.phenotype).toBeDefined();
      expect(typeof profile.cyp2c19.activity).toBe('number');
    });
  });

  describe('APOE genotype', () => {
    it('should determine APOE e3/e4 from rs429358=CT, rs7412=CC', () => {
      expect(profile.apoe.genotype).toContain('e3/e4');
    });
  });

  describe('risk scores', () => {
    it('should have global risk score in [0, 1]', () => {
      expect(profile.riskScores.global).toBeGreaterThanOrEqual(0);
      expect(profile.riskScores.global).toBeLessThanOrEqual(1);
    });

    it('should have all category scores defined', () => {
      expect(typeof profile.riskScores.cancer).toBe('number');
      expect(typeof profile.riskScores.cardiovascular).toBe('number');
      expect(typeof profile.riskScores.neurological).toBe('number');
      expect(typeof profile.riskScores.metabolism).toBe('number');
    });

    it('should have category scores in [0, 1]', () => {
      for (const key of ['cancer', 'cardiovascular', 'neurological', 'metabolism'] as const) {
        expect(profile.riskScores[key]).toBeGreaterThanOrEqual(0);
        expect(profile.riskScores[key]).toBeLessThanOrEqual(1);
      }
    });
  });

  describe('profile vector', () => {
    it('should be a 64-dimensional Float32Array', () => {
      expect(profile.profileVector).toBeInstanceOf(Float32Array);
      expect(profile.profileVector.length).toBe(64);
    });

    it('should be L2-normalised (magnitude ~1.0)', () => {
      let sumSq = 0;
      for (let i = 0; i < profile.profileVector.length; i++) {
        sumSq += profile.profileVector[i] * profile.profileVector[i];
      }
      const magnitude = Math.sqrt(sumSq);
      expect(magnitude).toBeCloseTo(1.0, 1);
    });
  });

  describe('drug recommendations', () => {
    it('should generate recommendations for non-Normal metabolisers', () => {
      // If CYP2D6 is non-Normal, we expect at least codeine/tramadol/tamoxifen recs
      if (profile.cyp2d6.phenotype !== 'Normal') {
        const cyp2d6Recs = profile.drugRecommendations.filter(r => r.gene === 'CYP2D6');
        expect(cyp2d6Recs.length).toBeGreaterThan(0);
        for (const rec of cyp2d6Recs) {
          expect(rec.drug).toBeDefined();
          expect(rec.phenotype).toBe(profile.cyp2d6.phenotype);
          expect(typeof rec.doseFactor).toBe('number');
        }
      }
    });

    it('should not generate recommendations for Normal metabolisers', () => {
      if (profile.cyp2c19.phenotype === 'Normal') {
        const cyp2c19Recs = profile.drugRecommendations.filter(r => r.gene === 'CYP2C19');
        expect(cyp2c19Recs.length).toBe(0);
      }
    });

    it('should have valid dose factors', () => {
      for (const rec of profile.drugRecommendations) {
        expect(rec.doseFactor).toBeGreaterThanOrEqual(0);
        expect(rec.doseFactor).toBeLessThanOrEqual(1.5);
      }
    });
  });
});
